name: Runtime

on:
  push:
    paths:
    - '*'
    - '!*.md'
    - '.github/workflows/runtime.yml'
    - 'checkouts/**'
    - 'config/**'
    - 'lib/**'
    - 'm4/**'
    - 'plugins/**'
    - 'rel/**'
  pull_request:
    paths:
    - '*'
    - '!*.md'
    - '.github/workflows/runtime.yml'
    - 'checkouts/**'
    - 'config/**'
    - 'lib/**'
    - 'm4/**'
    - 'plugins/**'
    - 'rel/**'

jobs:

  rebar:
    name: Rebar
    strategy:
      fail-fast: false
      matrix:
        otp: ['26', '27']
        rebar: ['rebar3']
    runs-on: ubuntu-22.04
    container:
      image: erlang:${{ matrix.otp }}

    steps:

    - uses: actions/checkout@v4

    - name: Prepare libraries
      run: |
        apt-get -qq update
        apt-get purge -y libgd3 nginx
        apt-get -qq install libexpat1-dev libgd-dev libpam0g-dev \
                            libsqlite3-dev libwebp-dev libyaml-dev

    - name: Cache Hex.pm
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/rebar3/
        key: ${{matrix.otp}}-${{hashFiles('rebar.config')}}

    - name: Compile
      run: |
        ./autogen.sh
        ./configure --with-rebar=./${{ matrix.rebar }} \
                    --prefix=/tmp/ejabberd \
                    --enable-all \
                    --disable-elixir \
                    --disable-tools \
                    --disable-odbc
        make

    - run: make xref

    - name: Run rel
      run: |
        make rel
        _build/prod/rel/ejabberd/bin/ejabberdctl start \
          && _build/prod/rel/ejabberd/bin/ejabberdctl started
        _build/prod/rel/ejabberd/bin/ejabberdctl register user1 localhost s0mePass
        _build/prod/rel/ejabberd/bin/ejabberdctl registered_users localhost > registered.log
        _build/prod/rel/ejabberd/bin/ejabberdctl stop \
          && _build/prod/rel/ejabberd/bin/ejabberdctl stopped
        mv _build/prod/rel/ejabberd/*.tar.gz _build/prod/rel/yo.${{matrix.otp}}.tar.gz
    
    - name: Archive release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          _build/prod/rel/ejabberd/*.tar.gz

    - name: Run dev
      run: |
        make dev
        _build/dev/rel/ejabberd/bin/ejabberdctl start \
          && _build/dev/rel/ejabberd/bin/ejabberdctl started
        _build/dev/rel/ejabberd/bin/ejabberdctl register user2 localhost s0mePass
        _build/dev/rel/ejabberd/bin/ejabberdctl registered_users localhost >> registered.log
        _build/dev/rel/ejabberd/bin/ejabberdctl stop \
          && _build/dev/rel/ejabberd/bin/ejabberdctl stopped

    - name: Run install
      run: |
        make install
        /tmp/ejabberd/sbin/ejabberdctl start \
          && /tmp/ejabberd/sbin/ejabberdctl started
        /tmp/ejabberd/sbin/ejabberdctl register user3 localhost s0mePass
        /tmp/ejabberd/sbin/ejabberdctl registered_users localhost >> registered.log
        /tmp/ejabberd/sbin/ejabberdctl stop \
          && /tmp/ejabberd/sbin/ejabberdctl stopped

    - name: View logs
      run: |
        echo "===> Registered:"
        cat registered.log
        echo "===> Prod:"
        cat _build/prod/rel/ejabberd/logs/*
        echo "===> Dev:"
        cat _build/dev/rel/ejabberd/logs/*
        echo "===> Install:"
        cat /tmp/ejabberd/var/log/ejabberd/*

    - name: Check logs
      run: |
        grep -q '^user1$' registered.log
        grep -q '^user2$' registered.log
        grep -q '^user3$' registered.log
        grep -q 'is started' _build/prod/rel/ejabberd/logs/ejabberd.log
        grep -q 'is stopped' _build/prod/rel/ejabberd/logs/ejabberd.log
        test $(find _build/prod/rel/ -empty -name error.log)
        grep -q 'is started' _build/dev/rel/ejabberd/logs/ejabberd.log
        grep -q 'is stopped' _build/dev/rel/ejabberd/logs/ejabberd.log
        test $(find _build/dev/rel/ -empty -name error.log)
        grep -q 'is started' /tmp/ejabberd/var/log/ejabberd/ejabberd.log
        grep -q 'is stopped' /tmp/ejabberd/var/log/ejabberd/ejabberd.log
        test $(find /tmp/ejabberd/var/log/ejabberd/ -empty -name error.log)

    - name: View logs failures
      if: always()
      run: |
        cat _build/prod/rel/ejabberd/logs/ejabberd.log
        cat _build/prod/rel/ejabberd/logs/error.log
        cat _build/dev/rel/ejabberd/logs/ejabberd.log
        cat _build/dev/rel/ejabberd/logs/error.log
        cat /tmp/ejabberd/var/log/ejabberd/ejabberd.log
        cat /tmp/ejabberd/var/log/ejabberd/error.log
